### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Yurasb** [v1-wizard/url_shortener#3]
`Traceback (most recent call last):
  File "src/main.py", line 1, in <module>
    from aiohttp import web
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 15, in <module>
    from . import (hdrs, web_exceptions, web_fileresponse, web_middlewares,
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 21, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'`

Need to update aiohttp up to 2.3.8 (latest - 2.3.9) at least where fixed yarl version (>=1.0.0) was added to dependencies

**Comment by v1-wizard** [comment]
Fixed in e0c594fd157ce2f72a44be527301737bafd63ec4.
